import './js/header.js';
import './js/hero.js';
import './js/pets-list-section.js';
import './js/about-us-section.js';
import './js/FAQ-section.js';
import './js/success-stories-section.js';
import './js/animal-details-modal.js';
import './js/order-modal.js';
import './js/footer.js';
